baseURL = 'https://jithusjacob.github.io/'
languageCode = 'en-us'
title = "jsj's notebook"
preserveTaxonomyNames = 'true'
[taxonomies]
  tag = 'tags'
  book = 'books'
  section = 'sections'
[params]
    dateFormat = "02 Jan 2006"